name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execution permission to gradlew
        run: chmod +x gradlew
      - name: Build
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
        run: ./gradlew clean compileJava jar shadowJar reobfJar publish
      - name: Save artifacts (for Paper)
        uses: actions/upload-artifact@v4
        with:
          name: UnknownNetworkBootstrap
          path: "build/libs/UnknownNetworkBootstrap.jar"
      - name: Save artifacts (for Spigot)
        uses: actions/upload-artifact@v4
        with:
          name: UnknownNetworkBootstrap-spigot
          path: "build/libs/UnknownNetworkBootstrap-spigot.jar"  