name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execution permission to gradlew
        run: chmod +x gradlew
      - name: Build
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
        run: ./gradlew clean compileJava jar shadowJar reobfJar
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          path: "build/libs/*UnknownNetworkCore*.jar"